### ISSUE TITLE
Separate devDependencies & dependencies

### ISSUE THREAD

**Issue by aksaha2311** [choonkending/react-webpack-node#101]
Now module like "babel-loader", includes under dependencies, which should be under devDependencies.

**Comment by choonkending** [comment]
@aksaha2311 Good point. The reason why I moved it to dependencies was because it gave me trouble with Heroku deployment. Babel-loader is still used as part of a post deployment task in order to build the js.

We can have a look at seeing how others manage their Heroku deployment and see if there s a nice way around this.

**Comment by choonkending** [comment]
Feel to reopen if u have any issues or concerns. Will close for now.
