### ISSUE TITLE
Load data from LocalStorage

### ISSUE THREAD

**Issue by danielstorch** [choonkending/react-webpack-node#111]
Hey,

sorry if there is already an answer or solution for this. Im not very experienced with Web development.

Where is the best place to load data from LocalStorage (if some exist) on client-side and dispatch them to the Redux storage?

My first guess would be in the `client.jsx` file. But it is only a render function?

Thanks for any help!

**Comment by psimyn** [comment]
You could initialise in client.jsx, that is where the initialState gets loaded. For example:

```
// Grab the state from a global injected into
// server-generated HTML
const initialState = JSON.parse(localStorage.getItem('initialState')) || window.__INITIAL_STATE__;
```

this would use the `initialState` value from localStorage if available, otherwise get the data from window.

If you wanted it in a specific component, I'd guess you could dispatch an action in `componentDidMount` ([Link](https://facebook.github.io/react/docs/component-specs.html#mounting-componentdidmount)) - it is run after first render, but only on the client.

Example:

```
componentDidMount() {
  const userId = JSON.parse(localStorage.getItem('userId'));
  dispatch(updateUser(userId));
}
```

**Comment by danielstorch** [comment]
Perfekt! 
Thanks for the Explanation

**Comment by choonkending** [comment]
@psimyn Awesome!

**Comment by choonkending** [comment]
Closing issue but happy to keep the discussion going!
