### ISSUE TITLE
markup generated on the server was not what the client was expecting

### ISSUE THREAD

**Issue by dcsan** [choonkending/react-webpack-node#113]
I'm getting this warning on reloading the app:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) 6xne2o.0"><a class="" href="/" data-reac
 (server) 6xne2o.0"><a class="navigation__item__27

**Comment by choonkending** [comment]
@dcsan Thanks for raising this as an issue. Were you running this on `npm run dev`? What happens here is when you make changes, `react-transform-hmr` reloads it and updates the markup on the browser ,but the server side markup was not changed from the initial state.

This will not be an issue in production because you will be running `npm run build && npm start` which will compile both the server and client side bundles with webpack. Let me know if that makes sense :)

**Comment by dcsan** [comment]
yes, this is in dev mode. 
maybe it happens when i have a bug in my code? At that point I'm seeing stale pages (served up from public I guess). So I have to stop the server and npm clean, and install everything again? Or just delete public? If that's the case then the server rendering is really not something I want during development.

**Comment by choonkending** [comment]
@dcsan Yep, if you are constantly making changes to your components and styling, I personally prefer not having to reload the page every time. It's an existing problem with devHotLoader on the flux/alt branch. :(

If you wanted to test server-side rendering on that branch, you'd have to run `npm run watch` and `npm run dev`, and refresh. Not an ideal flow. Out of curiosity, are you `flux/alt` instead of the master branch with redux because you are settled on `alt`?

**Comment by jrodl3r** [comment]
Also getting this error, even on something as simple as changing the text of an H1 tag.

Found that wrapping `${componentHTML}` in an extra div makes the warning stop happening after each reload (http://stackoverflow.com/a/33521172):

```<div id="app"><div>${componentHTML}</div></div>```

Are there any major issues with doing this?
