### ISSUE TITLE
Have to rerun `npm run build` on server side code change

### ISSUE THREAD

**Issue by charlieclark** [choonkending/react-webpack-node#133]
Unless I'm missing something, I'm under the impression that `npm run build` needs to be run everytime there is a change in a server-side file (eg. server.jsx or routes.js) Would be great if to have a watch flag or something on this task, since it takes quite a while to run.

**Comment by choonkending** [comment]
Good point! Thanks for raising this as an issue, it's been bugging me for a
while as well. Would you like to take a stab at it?

**Comment by charlieclark** [comment]
Yeah I'll take a look! Awesome work with this repo btw.

**Comment by caranicas** [comment]
I'd just like to +1 this.

**Comment by choonkending** [comment]
Agreed. Will take a look at this next in queue - after I have a bit of a poke around postcss :D

**Comment by dzotokan** [comment]
+1

**Comment by choonkending** [comment]
Will fix this after I have a bit of postcss fun :)

**Comment by choonkending** [comment]
Writing my thoughts down as I'm thinking of a good solution for this.

# What we want
On `npm run dev`, any changes to code should trigger a change and automatically reload.

## Problem
`react-transform-hmr` *only* works for any files from the entry point `client.jsx`. `webpack-dev-middleware` and `webpack-hot-middleware` currently only gets the `webpack.config.dev.js` and is compiled.

If you make changes to `server.jsx` or any files within the `server/` folder, nothing will happen, and you will have to re-run `npm run build` again for a new bundle.

## Potential solutions
**[Nodemon](https://github.com/remy/nodemon)** - nodemon will watch the files in the directory in which nodemon was started, and if any files change, nodemon will automatically restart your node application.

@psimyn suggested this to me aaages ago.

Here's a potential PR that still needs some work: https://github.com/choonkending/react-webpack-node/pull/162

## Couple of considerations

- Not a fan of having to `npm run build` for anything that involves `server.jsx`. Might have to have a dev version of the server bundle, to eliminate the uglifying.
- Also I'm not sure I like the idea of referencing a file that could potentially not exist (due to building), from [this](https://github.com/choonkending/react-webpack-node/blob/master/server/config/routes.js#L10) line. 

@psimyn Any ideas?

**Comment by psimyn** [comment]
@choonkending https://www.npmjs.com/package/hot-reload ?

**Comment by choonkending** [comment]
@psimyn What's the difference between that and nodemon? Not really sure how
this hot reloading is expected to work :(

**Comment by choonkending** [comment]
@charlieclark @dzotokan @psimyn @caranicas 

The PR will go out by the end of today - unless we find any :bug: (s). 

I'm going with the `nodemon` approach because it's simpler. (Nodemon watches for the files/folders you wish it to watch in `nodemon.json` and restarts the server, you will *still* have to refresh your page)

I think this is a good enough change and will significantly reduce developer frustration. Now you only need to run `npm run dev` without EVER running `npm run build`. #whatatimetobealive

----
Unrelated stuff

In the process, I considered not doing having separate bundles for client and server side webpack, i.e. by using **webpack-isomorphic-tools**, like [this](https://github.com/erikras/react-redux-universal-hot-example/blob/master/src/server.js#L66). 

That should be a separate PR if we find that we don't like our webpack config.

**Comment by choonkending** [comment]
Merged! Please re-open if you find an issue related to nodemon (or create a new issue).

**Comment by caranicas** [comment]
I'm in the midst of my own project for today, but I will spend tomorrow pulling this new base and moving my code over. Ill let you know how I like it.

**Comment by caranicas** [comment]
So i was trying to use this new version, and using nodemon it is still very slow when making a change to server code. I explored the webpack docs and found the` --watch ` command. I added to the `build:webpack` script in the package.json

`"build:webpack": "NODE_ENV=production webpack --progress --colors --watch --config ./webpack/webpack.config.prod.js",`

the only downside is i dont seem to be able to watch and  serve from the same process, so I have to open another terminal tab to run dev. But that seems like a small price to pay for a more quickly rebuilt app.

**Comment by choonkending** [comment]
@caranicas Might have not documented it well enough, but the recent change allows you to run just `npm run dev` without running `npm run build` any longer.

It have a separate server-side rendering webpack config that does not `uglify` the code so it should be relatively faster.

If you run 
```javascript
"dev": "NODE_ENV=development nodemon",
```

This in turn runs 

```javascript
"npm run build:dev && node server/index.js"
```
within the `nodemon.json` file. Only downside to this is if you make a change to server.jsx or any of the files watched by `nodemon`, you would still have to refresh the page. 

> the only downside is i dont seem to be able to watch and serve from the same process, so I have to open another terminal tab to run dev

When in `development` mode, you shouldn't ever have to run `npm run build:webpack` any longer. I've been doing this locally, but let me know if you find any problems. Happy to hop on a channel to chat if there's still something wrong with the config. Haven't tried using `dischord` yet haha, but we have gitter.
