### ISSUE TITLE
Might be worth mentioning in the setup to run npm install

### ISSUE THREAD

**Issue by sampattuzzi** [choonkending/react-webpack-node#142]
I (stupidly) came across this problem. Other starter kits run it by default with `npm start`. So it might be worth mentioning in the Readme that you need to run `npm install --dev` in order to build.

**Comment by choonkending** [comment]
Thanks for raising this issue! :+1: 

Good point about `npm install`.

I'd prefer having just a 
```
**Installation**
## You only need to run this once to install the required node modules
npm install

**Build**
```

So it would be easier to run for both `development` and `production`. Because depending on the node version you're using, `--dev` flag might actually be `--only=dev`. Hehe.

I'll make the above changes soon-ish. Let me know what you think!

**Comment by choonkending** [comment]
https://github.com/choonkending/react-webpack-node/commit/335529454065db7076c2538b38bcc8793d6b7f1a

There you go :) Closing, feel free to reopen if you think it should be improved!
