### ISSUE TITLE
fetchTopics called twice on server-side render

### ISSUE THREAD

**Issue by jdrmar** [choonkending/react-webpack-node#166]
Hi,

First of all thanks for your boilerplate. I'm just starting out and having all the pieces together helps me out a lot!
While trying to figure out which piece is doing what, I noticed that on the initial page render fetchItems is called twice.
I think this is caused by the line

const needs = components.reduce( (prev, current) => {
    return (current.need || [])
      .concat((current.WrappedComponent ? current.WrappedComponent.need : []) || [])
      .concat(prev);
    }, []);

in api/fetchComponentDataBeforeRender.js

where the wrappedComponent line causes the 'need' to be added to the 'needs', leading to fetchItems being called twice. Removing the line with wrappedComponent solves this problem, but I'm not sure if this is somehow caused by the react-router setup or if there's a better solution..

**Comment by Miauwi** [comment]
I think it happens because of
`export default connect(mapStateToProps)(Vote);`  in app/containers/Vote.jsx
react-redux module creates a wrapper element on Vote as far as I understand, and api/fetchComponentDataBeforeRender.js sees both components.

What I did to deal with it is, 

> const VotesWrap = connect(mapStateToProps,mapDispatchToProps)(Votes);
> VotesWrap .need = [
>   PostActions.fetchPosts
> ];
> export default VotesWrap 

so it only puts the 'statics.need' on the wrapper created by react-redux and work with that outside instead
by doing so you can also keep your Votes component as a 'dumb' component, like it's suggested by the redux developer. You can read about it  here
http://redux.js.org/docs/basics/UsageWithReact.html 
and
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0#.5lmffycdl
