### ISSUE TITLE
"constants" name conflict

### ISSUE THREAD

**Issue by JoelSanchez** [choonkending/react-webpack-node#205]
Hi, I experienced a problem using this boilerplate because this:

>  require("constants");

...imports a lot of constants that are unrelated to the app, supposedly they are internal to Node.js now, as mentioned [here](https://www.npmjs.com/package/constants).

So maybe it would be a good idea to rename "constants" to "types", since that's what they really are anyway.

**Comment by choonkending** [comment]
Interesting! We could call them `types` or `actionTypes` to be more explicit. 

I don't have an issue with renaming the file given the current behaviour resolves things incorrectly. 

Also feels like there should be a webpack config that needs to be fixed. Given in the future, we might have other files that are named the same as a Nodejs internal lib.

**Comment by choonkending** [comment]
I did a bit of digging into the webpack config. I think my understanding of `context`, `resolve.root` and `resolve.modulesDirectories` needs a bit of brushing up but it seems to me that we do not actually need `context`, and instead should just have `resolve.root`. 

In any case, I'm renaming constants to `types` because it makes sense semantically

**Comment by choonkending** [comment]
Based on [this](https://github.com/webpack/webpack/issues/2119#issuecomment-204755403) issue, it doesn't seem like we're the only ones facing this problem.
