### ISSUE TITLE
Still logged-in after logout

### ISSUE THREAD

**Issue by Grungla** [choonkending/react-webpack-node#212]
After logout, when you refresh the page it logs you back in.

**Comment by huyphamily** [comment]
I think it's a passport issue.

The issue here:
https://github.com/jaredhanson/passport/issues/246

stack overflow discussion here:
http://stackoverflow.com/questions/13758207/why-is-passportjs-in-node-not-removing-session-on-logout

I haven't had a chance to try anything out yet, but take a look and let me know what you ended up doing.

**Comment by choonkending** [comment]
Thanks for raising this issue.

Could be sessions not working for you. If you're in production , you're
expected to have a HTTPS connection.

I'll have a look whether we regressed or not.

**Comment by Grungla** [comment]
Hi huyphamily 

I looked over it and I solved it buy changing **resave** option to **false** inside server > config > express, thanks for the help though.

**Comment by choonkending** [comment]
@Grungla Sorry it took a while for me to get back to you. Yep, it's definitely an issue.

**Comment by choonkending** [comment]
Pushed a fix for it. Thanks!
