### ISSUE TITLE
What are routes inside config

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#234]
I am trying to clear up the package and am not sure if I can safely remove routes, it seems that they are specified there for database purposes and I am not using database. I wanted to find out what their purpose is and how they work?

**Comment by psimyn** [comment]
the routes in server are used to fetch data and give it to the react components - so if you have no db they can be removed.

Easiest thing to start with is to comment out the `routesConfig(app)` line in `server/index.js` (there is a comment about exactly this). You may also need to make some changes to `server.jsx` since it currently gets data from the routes

Please re-open or comment if you need any more help
