### ISSUE TITLE
Can't set api inside server.jsx

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#250]
I'm trying to configure axios to use my own api via:

```
const clientConfig = {
  host: 'staging-api.myapp.io/v1',
  port: '443'
}

// configure baseURL for axios requests (for serverside API calls)
axios.defaults.baseURL = `https://${clientConfig.host}:${clientConfig.port}`
```

And call it inside actions like so:

```
return request({
      method: 'post',
      url: '/waiting-list',
      data: {
        email,
        referral_code: refCode
      }
})
```

but all requests go to localhost:3000/waiting-list not sure entirely to what I am doing wrong

**Comment by MsUzoAgu** [comment]
hi @IljaDaderko did you figure out what the problem/issue was?

**Comment by IljaDaderko** [comment]
@MsUzoAgu No, waiting for reply here for any ideas of what could be causing the issue. You came across it as well?

**Comment by MsUzoAgu** [comment]
@IljaDaderko: First question I have is: are you running app in dev mode? If so then all requests will always go to localhost:3000 (using rails).

**Comment by IljaDaderko** [comment]
@MsUzoAgu ah, that could be an issue, is there a way to make it respect new api setup even in dev mode?

**Comment by MsUzoAgu** [comment]
@IljaDaderko: Not that I am aware of. 

My question would "what are trying to achieve/test right now? My guess is that you are trying to see if your api setup works correct right? But under the url `localhost:3000/waiting-list` you are getting some type of error (probably a route not found error. Is this true?

**Comment by IljaDaderko** [comment]
@MsUzoAgu Essentially I am working on localhost and trying to test my web app, to do so I need it to perform api calls, therefore I want to work on localhost:3000 but instead of calling localhost:3000/waiting-list call myApi.com/waiting-list

**Comment by MsUzoAgu** [comment]
@IljaDaderko: Given the information at hand, as far as I know you only have access to `myAPi.com/waiting-list` in production not in dev mode. To access `myAPi.com/waiting-list` you need to deploy your application (and I am saying this with the assumption that myApi.com is a domain you have)

Last question: Why do you want to call `myAPi.com/waiting-list` in dev mode? Are you getting any errors? 

I would say that if your app works well in dev mode then no need to see how it works in production mode mostly because the way it works in dev mode is most likely (minus some css/js hick ups) how it is going to run in production mode. But that is just my opinion.

Maybe someone

**Comment by psimyn** [comment]
in this case I think you will still want axios baseUrl to be localhost (since the browser -> server requests are still localhost:3000). For the specific requests you are sending to the external page, you can pass an absolute url to `request` and then it'll ignore baseUrl.

Example 
```
const baseUrl = 'https://staging-api.myapp.io/v1'; // empty string for regular dev/prod mode

return request({
      method: 'post',
      url: '${baseUrl}/waiting-list',
      data: {
        email,
        referral_code: refCode
      }
})
```
