### ISSUE TITLE
Adding gZip compression plugin 

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#278]
I am following this tutorial on adding a gZip compression to webpack: http://forum.vuejs.org/topic/4059/adding-gzip-to-webpack-using-compression-plugin

Wanted to check if I am doing this correctly by only adding it to the `webpack.config.prod.js` or should I also add it to others?

**Comment by caranicas** [comment]
that sounds right to me, I was actually about to look into this, after checkout out my google speed test. uncompressed images are killing my score.

**Comment by IljaDaderko** [comment]
@caranicas same situation, I'll let you know how it goes for me, probably will try it out over the weekend.

**Comment by caranicas** [comment]
@IljaDaderko add your project to the new 'docs/app.md' file. We are compiling a list of projects that use the boilerplate, and right now I'm the only one on the list.

**Comment by psimyn** [comment]
@caranicas if you are wanting to minify images you are probably better off automating image optimization. Can try something like https://github.com/tcoopman/image-webpack-loader (I haven't tested, but assume it's a webpack wrapper for imagemin). Generally gzip on properly optimized images should have negligible effect.

@IljaDaderko you're right about only needing it in prod config. For actual prod environments I generally add uncompressed compiled files, and then either the server ([express plugin](https://github.com/expressjs/compression)) or a CDN can do it.

**Comment by jrodl3r** [comment]
you can enable gzip w/ Express in `/server/config/express.js`

```javascript
import gzip from 'compression';

if (ENV === 'production') {
  app.use(gzip());
}
```

**Comment by caranicas** [comment]
@jrodl3r care to offer a pull request with that added in?

**Comment by jrodl3r** [comment]
@caranicas not sure which method would be more applicable...

there's also this: https://github.com/webpack/compression-webpack-plugin

also not sure if _**gZip**_ is an option everyone would want enabled by default.

Maybe add it as commented-out in express config... Dunno, seems so trivial to add, even on AWS/cPanel... maybe see what everybody else thinks first?

**Comment by caranicas** [comment]
@jrodl3r its not something that I had previously concerned myself with, but there doesn't seem to be much of a downside to adding it. [Losing IE6 support](http://techin.oureverydaylife.com/disadvantages-compressing-website-19600.html) ?? 

@IljaDaderko  and I both ran into the issue when Google brought it up. I don't blindly follow everything Google says, but if they are saying it would be beneficial to gzip your assets to delivery your site more quickly, I think they probably know what they are talking about. 

And then I was just listening to the latest episode of [javascrip jabber](https://devchat.tv/js-jabber/218-jsj-ember-js-with-yehuda-katz) and they had Yehuda Katz on as a guest talking about Ember. He said the point of a framework is to solve problems that people didn't know they had. I think compression falls under this. I think as long as we declare it in the readme under features it should be cool. Those that are too naive to know what it is will receive the benefits of it, and anyone that purposefully interested in not compressing their assets would you could safely assume have the skills needed to know where to look to remove it. 


@choonkending 
As a side note. if we could get the [page speed(https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Freact-webpack-node.herokuapp.com%2F&tab=mobile) numbers a better then we could actually advertise that as a feature as well.

**Comment by jrodl3r** [comment]
Great points, certainly wouldn't mind it being in there.

Which method do you prefer?

I'd suggest the Express option because it's more "out of the way," and I prefer to keep those webpack config files as clean and dry as possible (they can appear overly complex, to newcomers at first glance). 

Then again... What about external / CDN assets? Someone who builds all their assets with webpack, and then chucks a /gz folder up on AWS... They'd probably prefer the webpack plugin option.

Hrmmz...

**Comment by choonkending** [comment]
I'm a bit late in joining the party! Awesome discussion!

I'd prefer the gzipping done on `express` as @jrodl3r suggested, mainly because it will keep the webpack config files clean. 

Webpack holds a lot of image bundling responsibilities, and it makes sense for it to handle gzipping. However, adding gzipping to the webpack config might increase a bit of mental overhead for developers and newcomers. Perhaps we can still decrease the power of our webpack configs,  and let `express` / `nginx` whatever edge node handle the optimisation.

I might back track on the above statement, but if possible, let's go with the simplest optimisation that @jrodl3r suggested and roll with that. If we find ever find that external assets _really_ need to be built by webpack and that external server does not handle optimization, we will worry about that then?

@caranicas Yes! Good idea for page speed. (Urgh, 66/100 on mobile is causing my eyes to bleed)

**Comment by caranicas** [comment]
sounds good to me. I can offer a PR today or tomorrow. Figure I'll wrap it in the production flag too?

**Comment by choonkending** [comment]
:+1

**Comment by choonkending** [comment]
Closing this issue, but feel free to continue the discussion!

Also created a separate issue regarding pageSpeed #371
