### ISSUE TITLE
Long term caching of bundle

### ISSUE THREAD

**Issue by vierja** [choonkending/react-webpack-node#282]
### Description
- Type: Enhancement
----------------------------------------------------------------
## Enhancement

I am trying to use [long term caching](https://webpack.github.io/docs/long-term-caching.html) but the server has the /assets/app.js route/file fixed. How can I force webpack to update it, or use a variable to assign the right hash/route.

BTW, Awesome boilerplate, I was able to easily use it in a weekend to (re)build this: [Logprecios](http://www.logprecios.com).

**Comment by psimyn** [comment]
The link you included has most of the things you need.

1. Update `webpack.config.prod.js`, change to `filename: "[name].[hash].js"`

Now after prod build you'll have a file called something like `public/assets/app.a657812de.js`

2. Update either build task (add `--json`) or webpack config as described in [get filenames from stats](https://webpack.github.io/docs/long-term-caching.html#get-filenames-from-stats). With this you can output a JSON file, or something else (if you use plugin)

3. Update `app/server.jsx` to get passed a file path instead of the hardcoded one. Not sure of best/correct way to do this, but maybe update `server/index.js` to import the json file, then pass the path to App

Hope this helps a bit. And add you weekend project to https://github.com/choonkending/react-webpack-node/issues/277 !
