### ISSUE TITLE
Design Patterns

### ISSUE THREAD

**Issue by serranoarevalo** [choonkending/react-webpack-node#287]
### Description
- Type: Question
-----------------------------------------------------------------

## Question

First of all thank you for this fantastic tool, it has really helped me a lot to learn. Although a little bit intimidating when taking a first look at the code it's been a wonderful learning experience.

I'd like to know which design pattern is being followed here, it's the first time I see this folder organization with index.js referencing all the other scripts and the modularization in the server and in the client, I think it's fantastic and I'd like to learn more about building webapps with this patterns.

Thank you for your time and attention!

**Comment by caranicas** [comment]
Hey. Welcome to the project. Glad you are enjoying it. I've been using it for a few months now and it is absolutely fantastic.  

Maybe @chookending can speak more to the pattern. But I would just call it the separation of concerns into modules. Most of the time people don't take the care to maintain modularity when building a boilerplate.  They are much more interested in a proof of concept than a best practice. 

Working with a high degree of modularity makes the initial architecture and download a a bit more cumbersome because code exists in a lot of places and you need to understand not only the code work but how it links together.

However once you are up to speed it makes understand where the code you need to write should go.  This helps keep things consistent across teams.

**Comment by choonkending** [comment]
@serranoarevalo Welcome! :)

It's exactly as @caranicas explained!

I'm not sure what the design pattern is called either, it reminds me very much of the [revealing module](https://addyosmani.com/resources/essentialjsdesignpatterns/book/#revealingmodulepatternjavascript) but on a folder level. 

Using an `index.js` for each `module` or `component` exposes a public API of sorts, so that anything consuming that `module` could just require it like this:

```javascript
import { SomeComponent } from 'path/to/module'; // Notice we don't need to go to index.js
```

It's useful to keep us mindful of what we actually want to expose to components outside this folder. 

Also:

If you are interested in the folder structure organisation, there is also a discussion in this PR https://github.com/choonkending/react-webpack-node/pull/260.

Hopefully that helps!
