### ISSUE TITLE
How to update other clients on a new topic event?

### ISSUE THREAD

**Issue by k1tzu** [choonkending/react-webpack-node#288]
### Description
- Type: Question

-----------------------------------------------------------------

## Question

I'm wondering why all clients of the site don't get newly created topics automatically(without page reload) and how to do it easier? I know how to do it with one line of code with socket.io, but how with react-redux? It's still a deep dark forest for me.
Can you please point me the right direction? How to send an update to all clients currently viewing Vote.jsx when someone adds a topic?
And not making whole db.collection.find() but only with the one updated line in case there're thousands of topics.

**Comment by caranicas** [comment]
i'm not sure how you would push info down without a socket connection.  @jrodl3r  asked a similar question #275, so maybe he has something working. I had pointed him to my pull request #253 where I implemented a chat client using socket.io it doesn't go into data fetching because but if you already know how to use sockets then it should give to a understanding for how you can hook them into redux.
