### ISSUE TITLE
static need only works if page is accessed from application not on page load

### ISSUE THREAD

**Issue by IljaDaderko** [choonkending/react-webpack-node#316]
I'm utalising `static need = [ fetchFromApi ]` approach to fetch some data before rendering a page, for some reason it only works if I access that component (page component) from my app, i.e. clicking a link in navigation.

It will not fire the `fetchFromApi` function if I say refresh that page component or access it through url. I don't know where to start looking for this issue, so any suggestions are welcome.

**Comment by caranicas** [comment]
i'm not sure that I have had that exact issue before, but I have had issues with pages loading properly if i hit them in the url, but then if i use a `<Link>` it will work. It usually means there is an error somewhere on the page, because every time i've had an issue with some weirdness i didn't understand it was always ended up being something that I messed up. I've found this to most often happen on pages that I required auth for.

Im not sure I have any suggestions other than remove all the interior components from the page and see if you can get it load on a dry open. if you can then just add components back in until you find the offending module.

**Comment by IljaDaderko** [comment]
@caranicas so will usage of sessionStorage on routes work? I thought that we try to access these on the server side for pre-render, hence sessionStorage is not avaliable. But in a nut shell, I think httpOnly secure cookies are somewhat better approach for security as they can't be accessed by js.

What I ended up doing is setting them to expire when my auth tokens expire and ever so often I would refresh a token during some api calls.
