### ISSUE TITLE
Why app.js weighs 1.34 MB

### ISSUE THREAD

**Issue by Grievoushead** [choonkending/react-webpack-node#69]
I did ```npm run build```
then started in production mode ```npm start```
and in the browser network I see that app.js  weighs 1.34 Mb when in your demo it's 408 Kb.

**Comment by choonkending** [comment]
@Grievoushead Thanks for commenting!

That's because when you run `npm run build` even in production mode you have to put a `-p` in the webpack config to minify the files.

What happens when I deploy to Heroku is that https://github.com/choonkending/react-webpack-node/blob/master/package.json#L16 line is run, where there is a `-p` parameter.

Alternatively, I can put UglifyJSPlugin in the webpack config. So our initial build will always be uglified.

**Comment by choonkending** [comment]
I've added a fix for this d2604a3513d3b575c594d324529b218fc4f85af1 and https://github.com/choonkending/react-webpack-node/commit/4f71ebd670bbfe6553284d95383107c566b747d9. Let me know if this helps. :)

**Comment by Grievoushead** [comment]
Great!, Thanks :)
