### ISSUE TITLE
App Inexplicably Hangs

### ISSUE THREAD

**Issue by nicholasalanbrown** [choonkending/react-webpack-node#99]
This seems like a great boilerplate and generally things are going according to plan, but twice now after running ```npm run build && npm run dev``` and working with the app for a while, it will suddenly die inexplicably The terminal output will show the server is still running, but in my browser I just get ```Waiting for localhost...``` no matter what I do. The only thing that seems to fix it is restarting my computer and clearing the ```/public``` directory. Restarting the Node server doesn't help at all.

Has anyone else had this issue? Right now this is a deal-breaker for using this to build out my project, as I get no console output in either the terminal or the browser and I'm not sure where to even start debugging.

**Comment by choonkending** [comment]
@nicholasalanbrown Thanks for raising this issue. :)

So far this has not happened to me yet, but I'd like to replicate this. My guess is that it could either be  uglifying the js or node sass consuming a lot of memory.

I recently had some problems with compiling because I did not update my node sass and sass loader. 

It's hard to isolate the issue here as there's no debugging information from the broswer or terminal.

1. When the app hangs, is there still a webpack bundle emitted in terminal as usual? And does the console in browser say the usual "updated" message?

2. Is there a repo somewhere we could have a look at? Or is it the exact same boilerplate code crashing?

3. If you comment out the uglifyjs part out of the webpack config, is there still a problem?

Ill have a play around longer and see if I can replicate the issue.
